/*
 * APIMATICCalculator.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/03/2016
 */
using System;

namespace APIMATICCalculator.PCL
{
    public partial class Configuration
    {
        //The base Uri for API calls
        public static string BaseUri = "http://examples.apimatic.io/apps/calculator";

    }
}